"""empty message

Revision ID: 8aba837b77d9
Revises: 1929c2b15e6a
Create Date: 2017-01-29 18:56:27.154858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aba837b77d9'
down_revision = '1929c2b15e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('efternavn', sa.String(length=250), nullable=True))
    op.add_column('user', sa.Column('fornavn', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fornavn')
    op.drop_column('user', 'efternavn')
    # ### end Alembic commands ###
