"""empty message

Revision ID: c9f053840a8f
Revises: e5e2d7bd71de
Create Date: 2017-02-05 15:50:12.142562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f053840a8f'
down_revision = 'e5e2d7bd71de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('list_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'list_order')
    # ### end Alembic commands ###
