"""empty message

Revision ID: e5e2d7bd71de
Revises: 
Create Date: 2017-01-30 21:52:07.838766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e2d7bd71de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fornavn', sa.String(length=250), nullable=True),
    sa.Column('efternavn', sa.String(length=250), nullable=True),
    sa.Column('tlf_nr', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.Binary(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=True),
    sa.Column('tlf_nr_confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('tlf_nr')
    )
    op.create_table('morgenmad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dato', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morgenmad')
    op.drop_table('templates')
    # ### end Alembic commands ###
