"""empty message

Revision ID: 1128714e6a13
Revises: 233ef44d1bd9
Create Date: 2017-02-06 20:37:48.655067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128714e6a13'
down_revision = '233ef44d1bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morgenmad_users',
    sa.Column('morgenmad_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['morgenmad_id'], ['morgenmad.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morgenmad_users')
    # ### end Alembic commands ###
