"""empty message

Revision ID: 233ef44d1bd9
Revises: 0d8d5a59f530
Create Date: 2017-02-06 19:56:51.100658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233ef44d1bd9'
down_revision = '0d8d5a59f530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('morgenmad', sa.Column('is_next', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('morgenmad', 'is_next')
    # ### end Alembic commands ###
